[package]
name = "syneroym-async-queue"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
syneroym-core.workspace = true
anyhow.workspace = true
hex.workspace = true
rusqlite.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true
