[package]
name = "syneroym-client-gateway"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
syneroym-core.workspace = true
syneroym-sdk.workspace = true
syneroym-rpc.workspace = true
syneroym-identity.workspace = true
syneroym-app-orchestration.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
serde.workspace = true
serde_json.workspace = true
dashmap.workspace = true
httparse.workspace = true
hex.workspace = true
rand.workspace = true

[dev-dependencies]
async-trait.workspace = true
tempfile.workspace = true
