[package]
name = "syneroym-app-host-native"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
syneroym-app-host.workspace = true
syneroym-wit-interfaces.workspace = true
syneroym-sandbox-wasm.workspace = true
syneroym-data-db.workspace = true
syneroym-data-blob.workspace = true
syneroym-data-keystore.workspace = true
syneroym-mqtt-broker.workspace = true
syneroym-rpc.workspace = true
syneroym-core.workspace = true
syneroym-conversation.workspace = true
syneroym-app-orchestration.workspace = true
wasmtime.workspace = true
tokio.workspace = true
tracing.workspace = true
dashmap.workspace = true
async-trait.workspace = true

[dev-dependencies]
syneroym-test-dual-build-fixture.workspace = true
syneroym-async-queue.workspace = true
tempfile.workspace = true
serde_json.workspace = true
ed25519-dalek.workspace = true
