//! Session management subcommands
//!
//! Commands to delegate session keys, open, inspect, refresh, and close
//! person sessions at the node auth service.

use std::{
    error::Error,
    fmt, fs,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, bail};
use clap::Subcommand;
use reqwest::{Client, Response, StatusCode};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use syneroym_core::protocol_utils::{SESSION_COOKIE_NAME, gateway_session_assertion};
use syneroym_identity::{
    DelegationCertificate, Identity, delegation::SCOPE_SESSION_AUTH, substrate,
};

use super::member_identity;
use crate::DEFAULT_GATEWAY_URL;

#[derive(Subcommand, Debug, Clone)]
pub enum SessionCommands {
    /// Generate a fresh temporary key pair and mint a DelegationCertificate
    /// signed by the master key.
    Delegate {
        /// Lifetime of the minted delegation certificate in hours.
        #[arg(long, default_value_t = 24)]
        expires_hours: u64,
        /// Output path for the session key JSON bundle.
        #[arg(long, default_value = "session-key.json")]
        out: PathBuf,
        /// Community registry to publish this person's master anchor to.
        #[arg(long)]
        registry_url: Option<String>,
    },
    /// Open a person session at the auth service.
    Login {
        #[arg(long, default_value = DEFAULT_GATEWAY_URL)]
        gateway_url: String,
        /// Login method: `delegated-key` (default) or `local`.
        #[arg(long, default_value = "delegated-key")]
        method: String,
        /// Path to a `session-key.json` bundle generated by `roymctl session
        /// delegate`.
        #[arg(long)]
        session_key_file: Option<PathBuf>,
        /// Identity name for local login method or for master key resolution.
        #[arg(long)]
        identity: Option<String>,
        /// Community registry to publish this person's master anchor to.
        #[arg(long)]
        registry_url: Option<String>,
        /// Lifetime of the minted delegation certificate in hours (if
        /// generating on the fly).
        #[arg(long, default_value_t = 24)]
        expires_hours: u64,
    },
    /// Who the node currently thinks this client is.
    Status {
        #[arg(long, default_value = DEFAULT_GATEWAY_URL)]
        gateway_url: String,
    },
    /// Print the stored token, for `curl -H "Authorization: Bearer $(...)"`.
    Token {
        #[arg(long, default_value = DEFAULT_GATEWAY_URL)]
        gateway_url: String,
    },
    /// Refresh the session token at the auth service.
    Refresh {
        #[arg(long, default_value = DEFAULT_GATEWAY_URL)]
        gateway_url: String,
    },
    /// End the session at the auth service and delete the local session file.
    Logout {
        #[arg(long, default_value = DEFAULT_GATEWAY_URL)]
        gateway_url: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionKeyBundle {
    pub temp_secret_key_hex: String,
    pub temp_did: String,
    pub certificate: DelegationCertificate,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct ChallengeResponse {
    nonce: String,
    node_did: String,
    expires_at_secs: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct LoginRequest {
    method: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    temp_did: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    delegation: Option<DelegationCertificate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    nonce: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    signature: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    identity: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct LoginResponse {
    token: String,
    person_did: String,
    expires_at_secs: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct WhoamiResponse {
    person_did: String,
    auth: String,
    expires_at_secs: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct StoredSession {
    gateway_url: String,
    node_did: String,
    person_did: String,
    token: String,
    expires_at_secs: u64,
}

fn sanitize_gateway_url(url: &str) -> String {
    url.chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '_' }).collect()
}

fn session_file_path(dir: &Path, run_as: Option<&str>, gateway_url: &str) -> PathBuf {
    let gw_file = format!("{}.json", sanitize_gateway_url(gateway_url));
    match run_as {
        Some(id) => dir.join("sessions").join(id).join(gw_file),
        None => dir.join("sessions").join(gw_file),
    }
}

fn save_session_file(path: &Path, session: &StoredSession) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let data = serde_json::to_string_pretty(session)?;
    super::write_secret_file(path, data.as_bytes(), "session file")
}

fn persist_session(
    dir: &Path,
    run_as: Option<&str>,
    gateway_url: &str,
    session: &StoredSession,
) -> Result<()> {
    let path = session_file_path(dir, run_as, gateway_url);
    save_session_file(&path, session)
}

fn load_session_file(path: &Path) -> Result<StoredSession> {
    let data = fs::read_to_string(path)
        .with_context(|| format!("failed to read session file at {}", path.display()))?;
    serde_json::from_str(&data)
        .with_context(|| format!("invalid session JSON at {}", path.display()))
}

/// Returns `resp` unchanged if it is 2xx, else captures its status and
/// body -- the check-and-capture core shared by [`ensure_success`] and
/// [`ensure_login_success`], which only differ in how they turn a captured
/// failure into an error message.
async fn capture_failure(resp: Response) -> Result<Response, (StatusCode, String)> {
    if resp.status().is_success() {
        return Ok(resp);
    }
    let status = resp.status();
    let body = resp.text().await.unwrap_or_default();
    Err((status, body))
}

/// Bails with `{what} failed ({status}): {body}` when `resp` is not 2xx,
/// else passes it through unchanged.
async fn ensure_success(resp: Response, what: &str) -> Result<Response> {
    match capture_failure(resp).await {
        Ok(resp) => Ok(resp),
        Err((status, body)) => bail!("{what} failed ({status}): {body}"),
    }
}

/// Like [`ensure_success`], but for the login endpoints' richer error
/// shape: when the body is a JSON object carrying an `error` string, that
/// string is used instead of the raw body.
async fn ensure_login_success(resp: Response, what: &str) -> Result<Response> {
    match capture_failure(resp).await {
        Ok(resp) => Ok(resp),
        Err((status, body)) => {
            if let Ok(val) = serde_json::from_str::<Value>(&body)
                && let Some(err_msg) = val.get("error").and_then(|v| v.as_str())
            {
                bail!("{what} failed ({status}): {err_msg}");
            }
            bail!("{what} failed ({status}): {body}");
        }
    }
}

async fn handle_delegate(
    dir: &Path,
    run_as: Option<&str>,
    expires_hours: u64,
    out: &Path,
    registry_url: Option<&str>,
) -> Result<()> {
    let identity_name =
        run_as.context("session delegate requires --as <name> for the master identity")?;
    let key_path = dir.join("identities").join(format!("{identity_name}.key"));
    if !key_path.exists() {
        bail!("Identity '{}' not found at {}", identity_name, key_path.display());
    }
    let master_identity = Identity::load_from_path(&key_path)?;

    // Publish/refresh anchor on registry
    member_identity::refresh_anchor_or_warn(registry_url, &master_identity).await?;

    let temp_identity = Identity::generate()?;
    let temp_did = substrate::derive_did_key(&temp_identity.public_key());

    let cert = DelegationCertificate::issue(
        &master_identity,
        temp_identity.public_key(),
        expires_hours.saturating_mul(3600),
        SCOPE_SESSION_AUTH.to_string(),
    )?;

    let bundle = SessionKeyBundle {
        temp_secret_key_hex: hex::encode(temp_identity.to_bytes()),
        temp_did: temp_did.clone(),
        certificate: cert,
    };

    if let Some(parent) = out.parent()
        && !parent.as_os_str().is_empty()
    {
        fs::create_dir_all(parent)?;
    }
    let data = serde_json::to_string_pretty(&bundle)?;
    super::write_secret_file(out, data.as_bytes(), "session key file")?;

    println!(
        "Minted session delegation certificate for temporary DID {} -> {}",
        temp_did,
        out.display()
    );
    Ok(())
}

async fn login_local(
    dir: &Path,
    run_as: Option<&str>,
    gateway_url: &str,
    identity: Option<&str>,
) -> Result<()> {
    let local_identity =
        identity.or(run_as).context("local login requires --identity <name> or --as <name>")?;

    let client = Client::new();
    let base_url = gateway_url.trim_end_matches('/');
    let login_url = format!("{base_url}/_syneroym/session/login");
    let login_req = LoginRequest {
        method: "local".to_string(),
        temp_did: None,
        delegation: None,
        nonce: None,
        signature: None,
        identity: Some(local_identity.to_string()),
    };

    let resp = client
        .post(&login_url)
        .json(&login_req)
        .send()
        .await
        .with_context(|| format!("failed to connect to auth service at {login_url}"))?;
    let resp = ensure_login_success(resp, "login").await?;

    let grant: LoginResponse = resp.json().await?;
    let stored = StoredSession {
        gateway_url: gateway_url.to_string(),
        node_did: "local".to_string(),
        person_did: grant.person_did.clone(),
        token: grant.token,
        expires_at_secs: grant.expires_at_secs,
    };
    persist_session(dir, run_as, gateway_url, &stored)?;

    println!(
        "Logged in locally as {} (session expires at {})",
        grant.person_did, grant.expires_at_secs
    );
    Ok(())
}

/// Resolve the temporary identity and delegation certificate a
/// delegated-key login presents: read them from `session_key_file` if
/// given, else mint a fresh certificate under the master identity named
/// by `--as`, publishing its anchor first.
async fn resolve_delegated_session_key(
    dir: &Path,
    run_as: Option<&str>,
    session_key_file: Option<&Path>,
    registry_url: Option<&str>,
    expires_hours: u64,
) -> Result<(Identity, DelegationCertificate)> {
    if let Some(key_path) = session_key_file {
        let raw = fs::read_to_string(key_path).with_context(|| {
            format!("failed to read session key file at {}", key_path.display())
        })?;
        let bundle: SessionKeyBundle = serde_json::from_str(&raw).with_context(|| {
            format!("invalid session key bundle JSON at {}", key_path.display())
        })?;
        let secret_bytes: [u8; 32] = hex::decode(&bundle.temp_secret_key_hex)
            .context("invalid hex secret key in session key bundle")?
            .try_into()
            .map_err(|_| anyhow::anyhow!("secret key must be 32 bytes"))?;
        let temp_id = Identity::from_bytes(&secret_bytes);
        return Ok((temp_id, bundle.certificate));
    }

    let identity_name =
        run_as.context("delegated-key login requires --as <name> or --session-key-file <path>")?;
    let key_path = dir.join("identities").join(format!("{identity_name}.key"));
    if !key_path.exists() {
        bail!("Identity '{}' not found at {}", identity_name, key_path.display());
    }
    let master_identity = Identity::load_from_path(&key_path)?;

    // Publish/refresh anchor before login
    member_identity::refresh_anchor_or_warn(registry_url, &master_identity).await?;

    let temp_id = Identity::generate()?;
    let cert = DelegationCertificate::issue(
        &master_identity,
        temp_id.public_key(),
        expires_hours.saturating_mul(3600),
        SCOPE_SESSION_AUTH.to_string(),
    )?;
    Ok((temp_id, cert))
}

async fn login_delegated_key(
    dir: &Path,
    run_as: Option<&str>,
    gateway_url: &str,
    session_key_file: Option<&Path>,
    registry_url: Option<&str>,
    expires_hours: u64,
) -> Result<()> {
    let (temp_identity, cert) =
        resolve_delegated_session_key(dir, run_as, session_key_file, registry_url, expires_hours)
            .await?;
    let temp_did = substrate::derive_did_key(&temp_identity.public_key());

    let client = Client::new();
    let base_url = gateway_url.trim_end_matches('/');

    // 1. Fetch challenge
    let challenge_url = format!("{base_url}/_syneroym/session/challenge");
    let resp = client
        .post(&challenge_url)
        .send()
        .await
        .with_context(|| format!("failed to connect to auth service at {challenge_url}"))?;
    let resp = ensure_success(resp, "challenge request").await?;
    let ch: ChallengeResponse = resp.json().await?;

    // 2. Sign assertion
    let assertion = gateway_session_assertion(&ch.node_did, &ch.nonce, &cert.master_did);
    let signature = temp_identity.sign_json(&assertion)?;

    // 3. POST login
    let login_url = format!("{base_url}/_syneroym/session/login");
    let login_req = LoginRequest {
        method: "delegated-key".to_string(),
        temp_did: Some(temp_did),
        delegation: Some(cert.clone()),
        nonce: Some(ch.nonce),
        signature: Some(signature),
        identity: None,
    };
    let resp = client
        .post(&login_url)
        .json(&login_req)
        .send()
        .await
        .with_context(|| format!("failed to connect to auth service at {login_url}"))?;
    let resp = ensure_login_success(resp, "auth service login").await?;
    let grant: LoginResponse = resp.json().await?;

    // 4. Persist session
    let stored = StoredSession {
        gateway_url: gateway_url.to_string(),
        node_did: ch.node_did.clone(),
        person_did: grant.person_did.clone(),
        token: grant.token,
        expires_at_secs: grant.expires_at_secs,
    };
    persist_session(dir, run_as, gateway_url, &stored)?;

    println!(
        "Logged in as {} to node {} (session expires at {})",
        grant.person_did, ch.node_did, grant.expires_at_secs
    );
    Ok(())
}

#[allow(clippy::too_many_arguments)]
async fn handle_login(
    dir: &Path,
    run_as: Option<&str>,
    gateway_url: &str,
    method: &str,
    session_key_file: Option<&Path>,
    identity: Option<&str>,
    registry_url: Option<&str>,
    expires_hours: u64,
) -> Result<()> {
    if method == "local" {
        return login_local(dir, run_as, gateway_url, identity).await;
    }
    if method != "delegated-key" {
        bail!("unknown login method '{method}', supported methods are 'delegated-key' and 'local'");
    }
    login_delegated_key(dir, run_as, gateway_url, session_key_file, registry_url, expires_hours)
        .await
}

async fn handle_status(dir: &Path, run_as: Option<&str>, gateway_url: &str) -> Result<()> {
    let session_path = session_file_path(dir, run_as, gateway_url);
    if !session_path.exists() {
        bail!("no active session for {gateway_url}");
    }
    let session = load_session_file(&session_path)?;

    let client = Client::new();
    let base_url = gateway_url.trim_end_matches('/');
    let whoami_url = format!("{base_url}/_syneroym/session/whoami");
    let resp = client
        .get(&whoami_url)
        .header("Authorization", format!("Bearer {}", session.token))
        .header("Cookie", format!("{}={}", SESSION_COOKIE_NAME, session.token))
        .send()
        .await
        .with_context(|| format!("failed to connect to auth service at {whoami_url}"))?;
    let resp = ensure_success(resp, "session status check").await?;
    let whoami: WhoamiResponse = resp.json().await?;
    println!("Person DID: {}", whoami.person_did);
    println!("Auth: {}", whoami.auth);
    println!("Expires at: {}", whoami.expires_at_secs);
    Ok(())
}

fn handle_token(dir: &Path, run_as: Option<&str>, gateway_url: &str) -> Result<()> {
    let session_path = session_file_path(dir, run_as, gateway_url);
    if !session_path.exists() {
        bail!("no active session for {gateway_url}");
    }
    let session = load_session_file(&session_path)?;
    println!("{}", session.token);
    Ok(())
}

async fn handle_refresh(dir: &Path, run_as: Option<&str>, gateway_url: &str) -> Result<()> {
    let session_path = session_file_path(dir, run_as, gateway_url);
    if !session_path.exists() {
        bail!("no active session for {gateway_url}");
    }
    let session = load_session_file(&session_path)?;

    let client = Client::new();
    let base_url = gateway_url.trim_end_matches('/');
    let refresh_url = format!("{base_url}/_syneroym/session/refresh");
    let resp = client
        .post(&refresh_url)
        .header("Authorization", format!("Bearer {}", session.token))
        .header("Cookie", format!("{}={}", SESSION_COOKIE_NAME, session.token))
        .send()
        .await
        .with_context(|| format!("failed to connect to auth service at {refresh_url}"))?;
    let resp = ensure_success(resp, "session refresh").await?;
    let grant: LoginResponse = resp.json().await?;
    let stored = StoredSession {
        gateway_url: gateway_url.to_string(),
        node_did: session.node_did,
        person_did: grant.person_did.clone(),
        token: grant.token,
        expires_at_secs: grant.expires_at_secs,
    };
    persist_session(dir, run_as, gateway_url, &stored)?;

    println!("Refreshed session for {} (expires at {})", stored.person_did, stored.expires_at_secs);
    Ok(())
}

async fn handle_logout(dir: &Path, run_as: Option<&str>, gateway_url: &str) -> Result<()> {
    let session_path = session_file_path(dir, run_as, gateway_url);
    if session_path.exists() {
        if let Ok(session) = load_session_file(&session_path) {
            let client = Client::new();
            let base_url = gateway_url.trim_end_matches('/');
            let logout_url = format!("{base_url}/_syneroym/session/logout");
            let _ = client
                .post(&logout_url)
                .header("Authorization", format!("Bearer {}", session.token))
                .header("Cookie", format!("{}={}", SESSION_COOKIE_NAME, session.token))
                .send()
                .await;
        }
        let _ = fs::remove_file(&session_path);
    }
    println!("Logged out of {gateway_url}");
    Ok(())
}

pub async fn handle(command: &SessionCommands, dir: &Path, run_as: Option<&str>) -> Result<()> {
    match command {
        SessionCommands::Delegate { expires_hours, out, registry_url } => {
            handle_delegate(dir, run_as, *expires_hours, out, registry_url.as_deref()).await
        }
        SessionCommands::Login {
            gateway_url,
            method,
            session_key_file,
            identity,
            registry_url,
            expires_hours,
        } => {
            handle_login(
                dir,
                run_as,
                gateway_url,
                method,
                session_key_file.as_deref(),
                identity.as_deref(),
                registry_url.as_deref(),
                *expires_hours,
            )
            .await
        }
        SessionCommands::Status { gateway_url } => handle_status(dir, run_as, gateway_url).await,
        SessionCommands::Token { gateway_url } => handle_token(dir, run_as, gateway_url),
        SessionCommands::Refresh { gateway_url } => handle_refresh(dir, run_as, gateway_url).await,
        SessionCommands::Logout { gateway_url } => handle_logout(dir, run_as, gateway_url).await,
    }
}

pub async fn rpc_call(
    gateway_url: &str,
    host: Option<&str>,
    run_as: Option<&str>,
    ucan_path: Option<&Path>,
    dir: &Path,
    method: &str,
    params: Value,
) -> Result<Value> {
    // ucan_path: reserved for future UCAN proof attachment; not yet wired.
    let _ = ucan_path;
    let session_path = session_file_path(dir, run_as, gateway_url);
    let session =
        if session_path.exists() { Some(load_session_file(&session_path)?) } else { None };

    let client = Client::new();
    let base_url = gateway_url.trim_end_matches('/');
    let rpc_url = format!("{base_url}/rpc");

    let body = serde_json::json!({
        "jsonrpc": "2.0",
        "id": 1,
        "method": method,
        "params": params,
    });

    let mut req = client.post(&rpc_url).json(&body);

    if let Some(h) = host {
        req = req.header("Host", h);
    }

    if let Some(s) = session {
        req = req
            .header("Authorization", format!("Bearer {}", s.token))
            .header("Cookie", format!("{}={}", SESSION_COOKIE_NAME, s.token));
    }

    let resp =
        req.send().await.with_context(|| format!("failed to connect to gateway at {rpc_url}"))?;

    if !resp.status().is_success() {
        let status = resp.status();
        let err_text = resp.text().await.unwrap_or_default();
        return Err(RpcHttpError {
            method: method.to_string(),
            status: status.as_u16(),
            body: err_text,
        }
        .into());
    }

    let val: Value = resp.json().await?;
    if let Some(err) = val.get("error") {
        bail!("RPC error ({method}): {err}");
    }

    Ok(val.get("result").cloned().unwrap_or(Value::Null))
}

/// A non-2xx HTTP response from the gateway. Carries the status code as a
/// number so a caller can branch on it (e.g. 503 -> the node's own
/// guest-HTTP admission refused to start the call) instead of
/// substring-matching this type's `Display` text.
#[derive(Debug)]
pub struct RpcHttpError {
    pub method: String,
    pub status: u16,
    pub body: String,
}

impl fmt::Display for RpcHttpError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "RPC call to '{}' failed (HTTP {}): {}", self.method, self.status, self.body)
    }
}

impl Error for RpcHttpError {}
