//! Session management subcommands
//!
//! Commands to delegate session keys, open, inspect, refresh, and close
//! person sessions at the node auth service.

use std::{
    fs,
    io::Write,
    path::{Path, PathBuf},
};

use anyhow::{Context, Result, bail};
use clap::Subcommand;
use reqwest::Client;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use syneroym_core::protocol_utils::{SESSION_COOKIE_NAME, gateway_session_assertion};
use syneroym_identity::{
    DelegationCertificate, Identity, delegation::SCOPE_SESSION_AUTH, substrate,
};

use super::member_identity;
use crate::DEFAULT_GATEWAY_URL;

#[derive(Subcommand, Debug, Clone)]
pub enum SessionCommands {
    /// Generate a fresh temporary key pair and mint a DelegationCertificate
    /// signed by the master key.
    Delegate {
        /// Lifetime of the minted delegation certificate in hours.
        #[arg(long, default_value_t = 24)]
        expires_hours: u64,
        /// Output path for the session key JSON bundle.
        #[arg(long, default_value = "session-key.json")]
        out: PathBuf,
        /// Community registry to publish this person's master anchor to.
        #[arg(long)]
        registry_url: Option<String>,
    },
    /// Open a person session at the auth service.
    Login {
        #[arg(long, default_value = DEFAULT_GATEWAY_URL)]
        gateway_url: String,
        /// Login method: `delegated-key` (default) or `local`.
        #[arg(long, default_value = "delegated-key")]
        method: String,
        /// Path to a `session-key.json` bundle generated by `roymctl session
        /// delegate`.
        #[arg(long)]
        session_key_file: Option<PathBuf>,
        /// Identity name for local login method or for master key resolution.
        #[arg(long)]
        identity: Option<String>,
        /// Community registry to publish this person's master anchor to.
        #[arg(long)]
        registry_url: Option<String>,
        /// Lifetime of the minted delegation certificate in hours (if
        /// generating on the fly).
        #[arg(long, default_value_t = 24)]
        expires_hours: u64,
    },
    /// Who the node currently thinks this client is.
    Status {
        #[arg(long, default_value = DEFAULT_GATEWAY_URL)]
        gateway_url: String,
    },
    /// Print the stored token, for `curl -H "Authorization: Bearer $(...)"`.
    Token {
        #[arg(long, default_value = DEFAULT_GATEWAY_URL)]
        gateway_url: String,
    },
    /// Refresh the session token at the auth service.
    Refresh {
        #[arg(long, default_value = DEFAULT_GATEWAY_URL)]
        gateway_url: String,
    },
    /// End the session at the auth service and delete the local session file.
    Logout {
        #[arg(long, default_value = DEFAULT_GATEWAY_URL)]
        gateway_url: String,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionKeyBundle {
    pub temp_secret_key_hex: String,
    pub temp_did: String,
    pub certificate: DelegationCertificate,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct ChallengeResponse {
    nonce: String,
    node_did: String,
    expires_at_secs: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct LoginRequest {
    method: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    temp_did: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    delegation: Option<DelegationCertificate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    nonce: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    signature: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    identity: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct LoginResponse {
    token: String,
    person_did: String,
    expires_at_secs: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct WhoamiResponse {
    person_did: String,
    auth: String,
    expires_at_secs: u64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
struct StoredSession {
    gateway_url: String,
    node_did: String,
    person_did: String,
    token: String,
    expires_at_secs: u64,
}

fn sanitize_gateway_url(url: &str) -> String {
    url.chars().map(|c| if c.is_ascii_alphanumeric() { c } else { '_' }).collect()
}

fn session_file_path(dir: &Path, gateway_url: &str) -> PathBuf {
    dir.join("sessions").join(format!("{}.json", sanitize_gateway_url(gateway_url)))
}

fn save_session_file(path: &Path, session: &StoredSession) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    let data = serde_json::to_string_pretty(session)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::OpenOptionsExt;
        let mut file = fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o600)
            .open(path)
            .with_context(|| format!("failed to create session file at {}", path.display()))?;
        file.write_all(data.as_bytes())?;
    }
    #[cfg(not(unix))]
    {
        fs::write(path, data)?;
    }
    Ok(())
}

fn load_session_file(path: &Path) -> Result<StoredSession> {
    let data = fs::read_to_string(path)
        .with_context(|| format!("failed to read session file at {}", path.display()))?;
    serde_json::from_str(&data)
        .with_context(|| format!("invalid session JSON at {}", path.display()))
}

pub async fn handle(command: &SessionCommands, dir: &Path, run_as: Option<&str>) -> Result<()> {
    match command {
        SessionCommands::Delegate { expires_hours, out, registry_url } => {
            let identity_name =
                run_as.context("session delegate requires --as <name> for the master identity")?;
            let key_path = dir.join("identities").join(format!("{identity_name}.key"));
            if !key_path.exists() {
                bail!("Identity '{}' not found at {}", identity_name, key_path.display());
            }
            let master_identity = Identity::load_from_path(&key_path)?;

            // Publish/refresh anchor on registry
            member_identity::refresh_anchor_or_warn(registry_url.as_deref(), &master_identity)
                .await?;

            let temp_identity = Identity::generate()?;
            let temp_did = substrate::derive_did_key(&temp_identity.public_key());

            let cert = DelegationCertificate::issue(
                &master_identity,
                temp_identity.public_key(),
                expires_hours.saturating_mul(3600),
                SCOPE_SESSION_AUTH.to_string(),
            )?;

            let bundle = SessionKeyBundle {
                temp_secret_key_hex: hex::encode(temp_identity.to_bytes()),
                temp_did: temp_did.clone(),
                certificate: cert,
            };

            if let Some(parent) = out.parent()
                && !parent.as_os_str().is_empty()
            {
                fs::create_dir_all(parent)?;
            }
            let data = serde_json::to_string_pretty(&bundle)?;
            #[cfg(unix)]
            {
                use std::os::unix::fs::OpenOptionsExt;
                let mut file = fs::OpenOptions::new()
                    .write(true)
                    .create(true)
                    .truncate(true)
                    .mode(0o600)
                    .open(out)
                    .with_context(|| {
                        format!("failed to create session key file at {}", out.display())
                    })?;
                file.write_all(data.as_bytes())?;
            }
            #[cfg(not(unix))]
            {
                fs::write(out, data)?;
            }

            println!(
                "Minted session delegation certificate for temporary DID {} -> {}",
                temp_did,
                out.display()
            );
        }
        SessionCommands::Login {
            gateway_url,
            method,
            session_key_file,
            identity,
            registry_url,
            expires_hours,
        } => {
            let client = Client::new();
            let base_url = gateway_url.trim_end_matches('/');

            if method == "local" {
                let local_identity = identity
                    .as_deref()
                    .or(run_as)
                    .context("local login requires --identity <name> or --as <name>")?;

                let login_url = format!("{base_url}/_syneroym/session/login");
                let login_req = LoginRequest {
                    method: "local".to_string(),
                    temp_did: None,
                    delegation: None,
                    nonce: None,
                    signature: None,
                    identity: Some(local_identity.to_string()),
                };

                let resp =
                    client.post(&login_url).json(&login_req).send().await.with_context(|| {
                        format!("failed to connect to auth service at {login_url}")
                    })?;

                if !resp.status().is_success() {
                    let status = resp.status();
                    let err_text = resp.text().await.unwrap_or_default();
                    if let Ok(val) = serde_json::from_str::<Value>(&err_text)
                        && let Some(err_msg) = val.get("error").and_then(|v| v.as_str())
                    {
                        bail!("login failed ({status}): {err_msg}");
                    }
                    bail!("login failed ({status}): {err_text}");
                }

                let grant: LoginResponse = resp.json().await?;
                let session_path = session_file_path(dir, gateway_url);
                let stored = StoredSession {
                    gateway_url: gateway_url.clone(),
                    node_did: "local".to_string(),
                    person_did: grant.person_did.clone(),
                    token: grant.token,
                    expires_at_secs: grant.expires_at_secs,
                };
                save_session_file(&session_path, &stored)?;

                println!(
                    "Logged in locally as {} (session expires at {})",
                    grant.person_did, grant.expires_at_secs
                );
                return Ok(());
            }

            if method != "delegated-key" {
                bail!(
                    "unknown login method '{method}', supported methods are 'delegated-key' and \
                     'local'"
                );
            }

            // Delegated key flow
            let (temp_identity, cert) = if let Some(key_path) = session_key_file {
                let raw = fs::read_to_string(key_path).with_context(|| {
                    format!("failed to read session key file at {}", key_path.display())
                })?;
                let bundle: SessionKeyBundle = serde_json::from_str(&raw).with_context(|| {
                    format!("invalid session key bundle JSON at {}", key_path.display())
                })?;
                let secret_bytes: [u8; 32] = hex::decode(&bundle.temp_secret_key_hex)
                    .context("invalid hex secret key in session key bundle")?
                    .try_into()
                    .map_err(|_| anyhow::anyhow!("secret key must be 32 bytes"))?;
                let temp_id = Identity::from_bytes(&secret_bytes);
                (temp_id, bundle.certificate)
            } else {
                let identity_name = run_as.context(
                    "delegated-key login requires --as <name> or --session-key-file <path>",
                )?;
                let key_path = dir.join("identities").join(format!("{identity_name}.key"));
                if !key_path.exists() {
                    bail!("Identity '{}' not found at {}", identity_name, key_path.display());
                }
                let master_identity = Identity::load_from_path(&key_path)?;

                // Publish/refresh anchor before login
                member_identity::refresh_anchor_or_warn(registry_url.as_deref(), &master_identity)
                    .await?;

                let temp_id = Identity::generate()?;
                let cert = DelegationCertificate::issue(
                    &master_identity,
                    temp_id.public_key(),
                    expires_hours.saturating_mul(3600),
                    SCOPE_SESSION_AUTH.to_string(),
                )?;
                (temp_id, cert)
            };

            let temp_did = substrate::derive_did_key(&temp_identity.public_key());

            // 1. Fetch challenge
            let challenge_url = format!("{base_url}/_syneroym/session/challenge");
            let resp =
                client.post(&challenge_url).send().await.with_context(|| {
                    format!("failed to connect to auth service at {challenge_url}")
                })?;
            if !resp.status().is_success() {
                let status = resp.status();
                let err_text = resp.text().await.unwrap_or_default();
                bail!("challenge request failed ({status}): {err_text}");
            }
            let ch: ChallengeResponse = resp.json().await?;

            // 2. Sign assertion
            let assertion = gateway_session_assertion(&ch.node_did, &ch.nonce, &cert.master_did);
            let signature = temp_identity.sign_json(&assertion)?;

            // 3. POST login
            let login_url = format!("{base_url}/_syneroym/session/login");
            let login_req = LoginRequest {
                method: "delegated-key".to_string(),
                temp_did: Some(temp_did),
                delegation: Some(cert.clone()),
                nonce: Some(ch.nonce),
                signature: Some(signature),
                identity: None,
            };
            let resp = client
                .post(&login_url)
                .json(&login_req)
                .send()
                .await
                .with_context(|| format!("failed to connect to auth service at {login_url}"))?;

            if !resp.status().is_success() {
                let status = resp.status();
                let err_text = resp.text().await.unwrap_or_default();
                if let Ok(val) = serde_json::from_str::<Value>(&err_text)
                    && let Some(err_msg) = val.get("error").and_then(|v| v.as_str())
                {
                    bail!("auth service login failed ({status}): {err_msg}");
                }
                bail!("auth service login failed ({status}): {err_text}");
            }
            let grant: LoginResponse = resp.json().await?;

            // 4. Persist session
            let session_path = session_file_path(dir, gateway_url);
            let stored = StoredSession {
                gateway_url: gateway_url.clone(),
                node_did: ch.node_did.clone(),
                person_did: grant.person_did.clone(),
                token: grant.token,
                expires_at_secs: grant.expires_at_secs,
            };
            save_session_file(&session_path, &stored)?;

            println!(
                "Logged in as {} to node {} (session expires at {})",
                grant.person_did, ch.node_did, grant.expires_at_secs
            );
        }
        SessionCommands::Status { gateway_url } => {
            let session_path = session_file_path(dir, gateway_url);
            if !session_path.exists() {
                bail!("no active session for {gateway_url}");
            }
            let session = load_session_file(&session_path)?;

            let client = Client::new();
            let base_url = gateway_url.trim_end_matches('/');
            let whoami_url = format!("{base_url}/_syneroym/session/whoami");
            let resp = client
                .get(&whoami_url)
                .header("Authorization", format!("Bearer {}", session.token))
                .header("Cookie", format!("{}={}", SESSION_COOKIE_NAME, session.token))
                .send()
                .await
                .with_context(|| format!("failed to connect to auth service at {whoami_url}"))?;

            if !resp.status().is_success() {
                let status = resp.status();
                let err_text = resp.text().await.unwrap_or_default();
                bail!("session status check failed ({status}): {err_text}");
            }
            let whoami: WhoamiResponse = resp.json().await?;
            println!("Person DID: {}", whoami.person_did);
            println!("Auth: {}", whoami.auth);
            println!("Expires at: {}", whoami.expires_at_secs);
        }
        SessionCommands::Token { gateway_url } => {
            let session_path = session_file_path(dir, gateway_url);
            if !session_path.exists() {
                bail!("no active session for {gateway_url}");
            }
            let session = load_session_file(&session_path)?;
            println!("{}", session.token);
        }
        SessionCommands::Refresh { gateway_url } => {
            let session_path = session_file_path(dir, gateway_url);
            if !session_path.exists() {
                bail!("no active session for {gateway_url}");
            }
            let mut session = load_session_file(&session_path)?;

            let client = Client::new();
            let base_url = gateway_url.trim_end_matches('/');
            let refresh_url = format!("{base_url}/_syneroym/session/refresh");
            let resp = client
                .post(&refresh_url)
                .header("Authorization", format!("Bearer {}", session.token))
                .header("Cookie", format!("{}={}", SESSION_COOKIE_NAME, session.token))
                .send()
                .await
                .with_context(|| format!("failed to connect to auth service at {refresh_url}"))?;

            if !resp.status().is_success() {
                let status = resp.status();
                let err_text = resp.text().await.unwrap_or_default();
                bail!("session refresh failed ({status}): {err_text}");
            }
            let grant: LoginResponse = resp.json().await?;
            session.token = grant.token;
            session.expires_at_secs = grant.expires_at_secs;
            save_session_file(&session_path, &session)?;

            println!(
                "Refreshed session for {} (expires at {})",
                session.person_did, session.expires_at_secs
            );
        }
        SessionCommands::Logout { gateway_url } => {
            let session_path = session_file_path(dir, gateway_url);
            if session_path.exists() {
                if let Ok(session) = load_session_file(&session_path) {
                    let client = Client::new();
                    let base_url = gateway_url.trim_end_matches('/');
                    let logout_url = format!("{base_url}/_syneroym/session/logout");
                    let _ = client
                        .post(&logout_url)
                        .header("Authorization", format!("Bearer {}", session.token))
                        .header("Cookie", format!("{}={}", SESSION_COOKIE_NAME, session.token))
                        .send()
                        .await;
                }
                let _ = fs::remove_file(&session_path);
            }
            println!("Logged out of {gateway_url}");
        }
    }
    Ok(())
}
