name: 'CI E2E Tests'
description: 'Runs Playwright end-to-end tests'
runs:
  using: "composite"
  steps:
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      id: setup-chrome
      with:
        chrome-version: stable

    - name: Set Chrome Path
      run: echo "CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
      shell: bash

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '20'

    - name: Install Node Dependencies & Playwright Browsers
      working-directory: crates/substrate/tests/e2e
      run: |
        npm ci
        npx playwright install --with-deps chromium
      shell: bash

    - name: Run Playwright E2E Tests
      working-directory: crates/substrate/tests/e2e
      run: npm run test
      shell: bash

    - name: Upload Playwright Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: crates/substrate/tests/e2e/playwright-report/
        retention-days: 14
