package syneroym:core;

interface storage {
    /// Save a generic byte payload to the local store under a specific key
    put: func(key: string, data: list<u8>) -> result<_, string>;

    /// Retrieve data from the local store
    get: func(key: string) -> result<option<list<u8>>, string>;

    /// Delete data from the local store
    delete: func(key: string) -> result<_, string>;
}