name: 'CI Benchmarks'
description: 'Runs performance and benchmark tests'
inputs:
  release_flag:
    description: 'Flag to pass to cargo for release mode (e.g. --release)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Build WASM Test Component
      run: cd test-components/greeter && cargo component build --release --target wasm32-wasip2
      shell: bash

    - name: Build Performance Test Dependencies
      run: cargo build ${{ inputs.release_flag }} -p miniapp-demo1-web -p syneroym-substrate
      shell: bash

    - name: Run Cargo Bench
      run: cargo bench --workspace
      shell: bash

    - name: Run Latency Performance Tests
      run: cargo run ${{ inputs.release_flag }} -p syneroym-perf -- latency
      shell: bash

    - name: Run Concurrency Performance Tests
      run: cargo run ${{ inputs.release_flag }} -p syneroym-perf -- concurrency
      shell: bash
