[package]
name = "syneroym-roym-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
syneroym-app-host.workspace = true
syneroym-signed-record.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
syneroym-rpc.workspace = true
async-trait.workspace = true

[dev-dependencies]
toml.workspace = true

