name: 'CI Build and Test'
description: 'Compiles workspace and runs tests'
inputs:
  release_flag:
    description: 'Flag to pass to cargo for release mode (e.g. --release)'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Build WASM Test Component
      run: cd test-components/greeter && cargo component build --release --target wasm32-wasip2
      shell: bash

    - name: Run Tests
      run: cargo test --workspace --all-targets --all-features ${{ inputs.release_flag }}
      shell: bash
