name: Coverage

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip1

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install cargo-component
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-component@0.21.1

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
        
      - name: Build WASM Test Component
        run: cd test-components/introduce && cargo component build

      - name: Generate Code Coverage
        run: cargo llvm-cov --workspace --all-targets --all-features --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
