package syneroym:host;

interface context {
    // TODO: Currently a placeholder for context managed by host. Enhance later
    /// Returns a string incorporating the component context and request context.
    get-test-context: func(request-ctx: string) -> string;
}

interface app {
    /// Runs the application and returns a result string.
    run: func() -> string;
}

world host-environment {
    import context;
    export app;
}